name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.ipynb'
      - 'data/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install jq and moreutils (for sponge)
      run: |
        sudo apt-get install -y jq moreutils

    - name: Check out
      uses: actions/checkout@v1

    - name: Login into a registry
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build, tag and push
      run: |
        docker build -t chanwit/titanic-mlops-base:${{ github.sha }} .
        docker push chanwit/titanic-mlops-base:${{ github.sha }}
        docker tag chanwit/titanic-mlops-base:${{ github.sha }} chanwit/titanic-mlops-base:latest
        docker push chanwit/titanic-mlops-base:latest

    - name: Create changes back to Jupyter Notebook
      run: |
        jq '.metadata.kubeflow_noteobok.docker_image="chanwit/titanic-mlops-base:${{ github.sha }}"' < titanic_ml_comparision.ipynb | sponge titanic_ml_comparision.ipynb

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update image to chanwit/titanic-mlops-base:${{ github.sha }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}